# -*- coding: utf-8 -*-
"""earthquake.project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIFhsJF7J8gx9YA-w0IUm04dWZJ55TKB

#Earthquake Data
"""

import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = datetime.now().year - 5
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):

        start_date = f"{year}-{month:02d}-01"

        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        print(start_date, "→", end_date)

params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

response = requests.get(url, params=params)

#if response.status_code!=200:
  print("request failed:",response.text[:200])

data = response.json()

events = data.get("features", [])

for eq in events:
    props = eq["properties"]
    geo = eq["geometry"]

    all_records.append({
        "id": eq.get("id"),
        "time": props.get("time"),
        "updated": props.get("updated"),
        "latitude": geo["coordinates"][1],
        "longitude": geo["coordinates"][0],
        "depth_km": geo["coordinates"][2],
        "mag": props.get("mag"),
        "magType": props.get("magType"),
        "place": props.get("place"),
        "status": props.get("status"),
        "tsunami": props.get("tsunami"),
        "sig": props.get("sig"),
        "net": props.get("net"),
        "nst": props.get("nst"),
        "dmin": props.get("dmin"),
        "rms": props.get("rms"),
        "gap": props.get("gap"),
        "magError": props.get("magError"),
        "depthError": props.get("depthError"),
        "magNst": props.get("magNst"),
        "locationsource": props.get("locationSource"),
        "magsource": props.get("magSource"),
        "types": props.get("types"),
        "ids": props.get("ids"),
        "sources": props.get("sources"),
        "type": props.get("type")
    })

df = pd.DataFrame(all_records)
print(df.head())

df

df.columns

df["id"] = df["id"].astype(str)  # primary key
df["time"] = pd.to_datetime(df["time"])
df["updated"] = pd.to_datetime(df["updated"])
df["latitude"] = df["latitude"].astype(float)
df["longitude"] = df["longitude"].astype(float)
df["depth_km"] = df["depth_km"].astype(float)
df["mag"] = df["mag"].astype(float)
df["magType"] = df["magType"].astype(str)

df["place"] = df["place"].astype(str)
df["status"] = df["status"].astype(str)

df["rms"] = df["rms"].astype(float)
df["gap"] = df["gap"].astype(float)
df["magError"] = df["magError"].astype(float)
df["depthError"] = df["depthError"].astype(float)
df["magNst"] = df["magNst"].astype(float)
df["locationsource"] = df["locationsource"].astype(str)
df["magsource"] = df["magsource"].astype(str)
df["types"] = df["types"].astype(str)
df["ids"] = df["ids"].astype(str)
df["sources"] = df["sources"].astype(str)
df["type"] = df["type"].astype(str)

df["tsunami"] = df["tsunami"].astype(int)
df["sig"] = df["sig"].astype(int)

df["net"] = df["net"].astype(str)
df["nst"] = df["nst"].astype(float)
df["dmin"] = df["dmin"].astype(float)

df.isnull()

df.isnull().sum()

df.notnull().sum()

df.id.nunique()

df.id[df.id.duplicated()]

